/** Türkiye coğrafi bölgeleri (7) ve iller. Bölge adları veriyle eşleşecek şekilde kullanılır. */
export const BOLGELER_YK = [
  "Marmara",
  "Ege",
  "Karadeniz",
  "İç Anadolu",
  "Akdeniz",
  "Doğu Anadolu",
  "Güneydoğu Anadolu",
] as const;

export const BOLGE_ILLER: Record<string, string[]> = {
  Marmara: [
    "İstanbul",
    "Bursa",
    "Kocaeli",
    "Tekirdağ",
    "Çanakkale",
    "Balıkesir",
    "Yalova",
    "Sakarya",
    "Kırklareli",
    "Edirne",
    "Bilecik",
  ],
  Ege: [
    "İzmir",
    "Manisa",
    "Aydın",
    "Denizli",
    "Muğla",
    "Uşak",
    "Afyonkarahisar",
    "Kütahya",
  ],
  Karadeniz: [
    "Samsun",
    "Trabzon",
    "Ordu",
    "Giresun",
    "Rize",
    "Artvin",
    "Gümüşhane",
    "Bayburt",
    "Sinop",
    "Kastamonu",
    "Çorum",
    "Amasya",
    "Tokat",
    "Zonguldak",
    "Bartın",
    "Karabük",
    "Düzce",
    "Bolu",
  ],
  "İç Anadolu": [
    "Ankara",
    "Konya",
    "Kayseri",
    "Eskişehir",
    "Sivas",
    "Aksaray",
    "Niğde",
    "Nevşehir",
    "Kırıkkale",
    "Kırşehir",
    "Yozgat",
    "Çankırı",
  ],
  Akdeniz: [
    "Antalya",
    "Mersin",
    "Adana",
    "Hatay",
    "Kahramanmaraş",
    "Osmaniye",
    "Isparta",
    "Burdur",
  ],
  "Doğu Anadolu": [
    "Erzurum",
    "Erzincan",
    "Malatya",
    "Elazığ",
    "Bingöl",
    "Tunceli",
    "Ağrı",
    "Kars",
    "Iğdır",
    "Ardahan",
    "Muş",
    "Bitlis",
    "Van",
    "Hakkari",
  ],
  "Güneydoğu Anadolu": [
    "Gaziantep",
    "Şanlıurfa",
    "Diyarbakır",
    "Mardin",
    "Batman",
    "Siirt",
    "Şırnak",
    "Kilis",
    "Adıyaman",
  ],
};
